// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/applications" | "/admin/invoices" | "/admin/menu" | "/admin/orders" | "/admin/products" | "/admin/queries" | "/admin/retailers" | "/admin/sales" | "/admin/settings" | "/admin/website" | "/b2b" | "/b2b-clients" | "/blog" | "/brands" | "/contact-us" | "/login" | "/medical-patients" | "/privacy-policy" | "/register" | "/retailer" | "/retailer/account" | "/retailer/cart" | "/retailer/orders" | "/retailer/products" | "/retailers" | "/retailers/apply" | "/services" | "/shop" | "/subscription" | "/terms-of-use" | "/veterans"
type AppRouteHandlerRoutes = "/api/admin/account-changes" | "/api/admin/applications" | "/api/admin/create-retailer" | "/api/admin/menu" | "/api/admin/orders" | "/api/admin/queries" | "/api/admin/retailer-notes" | "/api/admin/retailers" | "/api/admin/site-content" | "/api/contact" | "/api/menu/products" | "/api/retailer/account" | "/api/retailer/debug" | "/api/retailer/orders" | "/api/retailer/submit-order" | "/api/retailers/apply" | "/api/site-content"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/contact-us"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/applications": {}
  "/admin/invoices": {}
  "/admin/menu": {}
  "/admin/orders": {}
  "/admin/products": {}
  "/admin/queries": {}
  "/admin/retailers": {}
  "/admin/sales": {}
  "/admin/settings": {}
  "/admin/website": {}
  "/api/admin/account-changes": {}
  "/api/admin/applications": {}
  "/api/admin/create-retailer": {}
  "/api/admin/menu": {}
  "/api/admin/orders": {}
  "/api/admin/queries": {}
  "/api/admin/retailer-notes": {}
  "/api/admin/retailers": {}
  "/api/admin/site-content": {}
  "/api/contact": {}
  "/api/menu/products": {}
  "/api/retailer/account": {}
  "/api/retailer/debug": {}
  "/api/retailer/orders": {}
  "/api/retailer/submit-order": {}
  "/api/retailers/apply": {}
  "/api/site-content": {}
  "/b2b": {}
  "/b2b-clients": {}
  "/blog": {}
  "/brands": {}
  "/contact-us": {}
  "/login": {}
  "/medical-patients": {}
  "/privacy-policy": {}
  "/register": {}
  "/retailer": {}
  "/retailer/account": {}
  "/retailer/cart": {}
  "/retailer/orders": {}
  "/retailer/products": {}
  "/retailers": {}
  "/retailers/apply": {}
  "/services": {}
  "/shop": {}
  "/subscription": {}
  "/terms-of-use": {}
  "/veterans": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/contact-us": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
