// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/b2b-clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/b2b-clients">> = Specific
  const handler = {} as typeof import("../../app/(public)/b2b-clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/b2b/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/b2b">> = Specific
  const handler = {} as typeof import("../../app/(public)/b2b/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/(public)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands">> = Specific
  const handler = {} as typeof import("../../app/(public)/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/contact-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-us">> = Specific
  const handler = {} as typeof import("../../app/(public)/contact-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/medical-patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/medical-patients">> = Specific
  const handler = {} as typeof import("../../app/(public)/medical-patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/(public)/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/retailers/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retailers/apply">> = Specific
  const handler = {} as typeof import("../../app/(public)/retailers/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/retailers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retailers">> = Specific
  const handler = {} as typeof import("../../app/(public)/retailers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../app/(public)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../app/(public)/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription">> = Specific
  const handler = {} as typeof import("../../app/(public)/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/terms-of-use/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-use">> = Specific
  const handler = {} as typeof import("../../app/(public)/terms-of-use/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/veterans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/veterans">> = Specific
  const handler = {} as typeof import("../../app/(public)/veterans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/applications">> = Specific
  const handler = {} as typeof import("../../app/admin/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invoices">> = Specific
  const handler = {} as typeof import("../../app/admin/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu">> = Specific
  const handler = {} as typeof import("../../app/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/queries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/queries">> = Specific
  const handler = {} as typeof import("../../app/admin/queries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/retailers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/retailers">> = Specific
  const handler = {} as typeof import("../../app/admin/retailers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sales">> = Specific
  const handler = {} as typeof import("../../app/admin/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/website/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/website">> = Specific
  const handler = {} as typeof import("../../app/admin/website/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/retailer/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retailer/account">> = Specific
  const handler = {} as typeof import("../../app/retailer/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/retailer/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retailer/cart">> = Specific
  const handler = {} as typeof import("../../app/retailer/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/retailer/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retailer/orders">> = Specific
  const handler = {} as typeof import("../../app/retailer/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/retailer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retailer">> = Specific
  const handler = {} as typeof import("../../app/retailer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/retailer/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/retailer/products">> = Specific
  const handler = {} as typeof import("../../app/retailer/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/account-changes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/account-changes">> = Specific
  const handler = {} as typeof import("../../app/api/admin/account-changes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/applications">> = Specific
  const handler = {} as typeof import("../../app/api/admin/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/create-retailer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-retailer">> = Specific
  const handler = {} as typeof import("../../app/api/admin/create-retailer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/locations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/menu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/menu">> = Specific
  const handler = {} as typeof import("../../app/api/admin/menu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders">> = Specific
  const handler = {} as typeof import("../../app/api/admin/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/queries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/queries">> = Specific
  const handler = {} as typeof import("../../app/api/admin/queries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/retailer-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/retailer-notes">> = Specific
  const handler = {} as typeof import("../../app/api/admin/retailer-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/retailers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/retailers">> = Specific
  const handler = {} as typeof import("../../app/api/admin/retailers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/site-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/site-content">> = Specific
  const handler = {} as typeof import("../../app/api/admin/site-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/upload-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/upload-image">> = Specific
  const handler = {} as typeof import("../../app/api/admin/upload-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/menu/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu/products">> = Specific
  const handler = {} as typeof import("../../app/api/menu/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retailer/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retailer/account">> = Specific
  const handler = {} as typeof import("../../app/api/retailer/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retailer/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retailer/debug">> = Specific
  const handler = {} as typeof import("../../app/api/retailer/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retailer/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retailer/locations">> = Specific
  const handler = {} as typeof import("../../app/api/retailer/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retailer/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retailer/orders">> = Specific
  const handler = {} as typeof import("../../app/api/retailer/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retailer/submit-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retailer/submit-order">> = Specific
  const handler = {} as typeof import("../../app/api/retailer/submit-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/retailers/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/retailers/apply">> = Specific
  const handler = {} as typeof import("../../app/api/retailers/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/site-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-content">> = Specific
  const handler = {} as typeof import("../../app/api/site-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(public)/contact-us/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact-us">> = Specific
  const handler = {} as typeof import("../../app/(public)/contact-us/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
