var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0aoh5sb._.js")
R.c("server/chunks/ssr/lib_data_getSiteContent_ts_0psrbap._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_16gxne5.js")
R.c("server/chunks/ssr/[root-of-the-server]__1liausz._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02l7d_r._.js")
R.c("server/chunks/ssr/app_layout_tsx_2144vk_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/node_modules_0m3gs-6._.js")
R.c("server/chunks/ssr/_1eaaa_k._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_page_actions_1oplbj7.js")
R.m(71521)
module.exports=R.m(71521).exports
